### ISSUE TITLE
Remove Versioning from docker-compose.yml File

### ISSUE THREAD

**Issue by Kumala3** [Latand/tgbot_template_v3#14]
# Description
Starting from Docker Desktop version **2.25.0**, it is no longer necessary to specify a version in the docker-compose.yml file. Instead, the use of versioning is considered obsolete and can lead to warnings such as:
`E:\Your_Directory\Project\docker-compose.yml: version is obsolete`

This warning indicates that the specified version in the `docker-compose.yml` file is **no longer required** and can be **safely removed** to align with the latest Docker Compose specifications.

## Steps to Resolve
Remove the version key: Delete the version key and its value from the docker-compose.yml file.
`Example Before:`
```yaml
version: '3.8'
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
```

`Example after:`
```yaml
services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
```

## Benefits
1. **Simplification**: The docker-compose.yml file will be simpler and less cluttered without the version key.
2. **Warning Elimination**: Removing the version key will prevent the obsolete version warning, providing a cleaner user experience.

## References

[Compose Specification: Version and Name Top-Level Elements](https://github.com/compose-spec/compose-spec/blob/master/spec.md#version-and-name-top-level-elements)
